name: 'oauth2-exchange-spring-boot-starter: deploy artifact on push'

on:
  pull_request:
    paths:
      - 'spring-boot/starter/**'
    branches:
      - 'main'
      - 'develop'

jobs:
  oauth2-exchange-spring-boot-starter-mvn-deploy-on-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/starter

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven

      - name: Publish with Maven
        run: mvn clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}