name: 'oauth2-exchange CI'

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'release/**'
      - 'tmp/**'

jobs:
  core-tests:
    name: 'oauth2-exchange-core: run tests'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build and verify with Maven
        run: mvn clean verify


  spring-boot-autoconfigure-tests:
    name: 'oauth2-exchange-spring-boot-autoconfigure: run tests'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/autoconfigure

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build and verify with Maven
        run: mvn clean verify


  spring-boot-starter-run-tests-on-pr:
    name: 'oauth2-exchange-spring-boot-starter: run tests'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/starter

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build and verify with Maven
        run: mvn clean verify