name: 'oauth2-exchange-spring-boot-autoconfigure: test on pull request'

on:
  pull_request:
    paths:
      - 'spring-boot/autoconfigure/**'
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'release/**'
      - 'tmp/**'

jobs:
  oauth2-exchange-spring-boot-autoconfigure-mvn-verify-on-pr:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/autoconfigure

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build and verify with Maven
        run: mvn clean verify