name: 'oauth2-exchange-spring-boot-autoconfigure: deploy artifact on push'

on:
  push:
    paths:
      - 'spring-boot/autoconfigure/**'
    branches:
      - 'main'
      - 'develop'

jobs:
  oauth2-exchange-spring-boot-autoconfigure-mvn-deploy-on-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/autoconfigure

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build and verify with Maven
        run: mvn clean deploy