name: 'oauth2-exchange CI'

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'release/**'
      - 'tmp/**'

jobs:
  tests:
    name: 'run tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build, verify and install with Maven (core)
        working-directory: core
        run: mvn clean install

      - name: Build, verify and install with Maven (spring-boot-autoconfigure)
        working-directory: spring-boot/autoconfigure
        run: mvn clean install

      - name: Build and verify with Maven (spring-boot-starter)
        working-directory: spring-boot/starter
        run: mvn clean install