name: 'oauth2-exchange-core: deploy snapshot'

on:
  push:
    paths:
      - 'core/**'
    branches:
      - 'develop'

jobs:
  oauth2-exchange-core-deploy-snapshot-on-push:
    name: 'oauth2-exchange-core: deploy snapshot'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven

      - name: Publish with Maven
        run: mvn clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}