name: 'oauth2-exchange CD (releases)'

on:
  release:
    types:
      - released

jobs:
  core-deploy-release:
    name: 'oauth2-exchange-core: deploy release'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven

      - name: Publish with Maven
        run: mvn clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


  spring-boot-autoconfigure-deploy-release:
    name: 'oauth2-exchange-spring-boot-autoconfigure: deploy release'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/autoconfigure

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven

      - name: Publish with Maven
        run: mvn clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


  spring-boot-starter-deploy-release:
    name: 'oauth2-exchange-spring-boot-starter: deploy release'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spring-boot/starter

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven

      - name: Publish with Maven
        run: mvn clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}